name: Metrics
on:
  schedule: [{ cron: "0 16 * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Medias
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: NOT_NEEDED

          base: ""
          base_hireable: yes

          # AniList
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: onetimelink
