name: Metrics
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Medias
        uses: lowlighter/metrics@latest
        with:
          filename: ./static/anilist.characters.svg
          token: NOT_NEEDED

          base: ""
          base_hireable: yes
          committer_branch: static/plugins

          # AniList
          plugin_anilist: yes
          plugin_anilist_shuffle: yes
          plugin_anilist_limit: ${{ secrets.ANILIST_LIMIT }} # number of rows to show
          plugin_anilist_limit_characters: ${{ secrets.ANILIST_LIMIT_CHARACTERS }} # number of items to show
          plugin_anilist_medias: ${{ secrets.ANILIST_MEDIAS }} # anime
          plugin_anilist_sections: ${{ secrets.ANILIST_MEDIAS_SECTIONS }} # characters
          plugin_anilist_user: ${{ secrets.ANILIST_USER }} # username
