name: Metrics
on:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to latest main
        run: |
          set -e
          git fetch origin main
          git checkout -B main
          git reset --hard origin/main

      - name: Medias
        uses: lowlighter/metrics@latest
        with:
          filename: static/anilist.characters.svg
          token: NOT_NEEDED
          config_display: large
          base: ""
          base_hireable: yes
          # Do NOT auto-commit from metrics; we'll commit the processed output ourselves
          # (omit committer_branch / committer_message)
          plugin_anilist: yes
          plugin_anilist_limit: ${{ vars.ANILIST_LIMIT_DESKTOP }}
          plugin_anilist_limit_characters: ${{ vars.ANILIST_LIMIT_CHARACTERS }}
          plugin_anilist_medias: ${{ vars.ANILIST_MEDIAS }}
          plugin_anilist_sections: ${{ vars.ANILIST_MEDIAS_SECTIONS }}
          plugin_anilist_user: ${{ secrets.ANILIST_USER }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Post-process SVG (inject AniList characters) for DESKTOP
        run: |
          python scripts/anilist.py \
            static/anilist.characters.desktop.svg \
            --source static/anilist.characters.svg \
            --output static/anilist.characters.desktop.svg \
            --max-images "${{ vars.ANILIST_LIMIT_CHARACTERS }}"

      - name: Post-process SVG (inject AniList characters) for MOBILE
        run: |
          python scripts/anilist.py \
            static/anilist.characters.mobile.svg \
            --source static/anilist.characters.svg \
            --output static/anilist.characters.mobile.svg \
            --max-images "${{ vars.ANILIST_LIMIT_CHARACTERS }}"

      - name: Commit processed SVG to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git rm -f --ignore-unmatch static/anilist.characters.svg
          git add -A static/

          git commit -m "chore(metrics): post-process AniList SVG [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main
