name: Metrics
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Mobile-optimized version
      - name: Medias (Mobile)
        uses: lowlighter/metrics@latest
        with:
          filename: static/anilist.characters.mobile.svg
          token: NOT_NEEDED
          config_display: regular # Mobile view width (common mobile resolution)
          base: ""
          base_hireable: yes
          committer_branch: static/plugins

          # AniList configuration
          plugin_anilist: yes
          plugin_anilist_limit: ${{ vars.ANILIST_LIMIT }}
          plugin_anilist_limit_characters: ${{ vars.ANILIST_LIMIT_CHARACTERS }}
          plugin_anilist_medias: ${{ vars.ANILIST_MEDIAS }}
          plugin_anilist_sections: ${{ vars.ANILIST_MEDIAS_SECTIONS }}
          plugin_anilist_user: ${{ secrets.ANILIST_USER }}

      # Desktop-optimized version
      - name: Medias (Desktop)
        uses: lowlighter/metrics@latest
        with:
          filename: static/anilist.characters.desktop.svg
          token: NOT_NEEDED
          config_display: large # Desktop view width (common desktop resolution)
          base: ""
          base_hireable: yes
          committer_branch: static/plugins

          # AniList configuration
          plugin_anilist: yes
          plugin_anilist_limit: ${{ vars.ANILIST_LIMIT }}
          plugin_anilist_limit_characters: ${{ vars.ANILIST_LIMIT_CHARACTERS }}
          plugin_anilist_medias: ${{ vars.ANILIST_MEDIAS }}
          plugin_anilist_sections: ${{ vars.ANILIST_MEDIAS_SECTIONS }}
          plugin_anilist_user: ${{ secrets.ANILIST_USER }}
